const state = { subjects: window.STUDY_CONTENT?.subjects || [], saved: JSON.parse(localStorage.getItem('study-pocket-saved') || '[]'), progress: JSON.parse(localStorage.getItem('study-pocket-progress') || '{}') };
const screen = document.getElementById('screen');

function esc(value) { return String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char])); }
function saveState() { localStorage.setItem('study-pocket-saved', JSON.stringify(state.saved)); localStorage.setItem('study-pocket-progress', JSON.stringify(state.progress)); }
function subjectById(id) { return state.subjects.find((subject) => subject.id === id); }
function topicById(subjectId, topicId) { return subjectById(subjectId)?.topics.find((topic) => topic.id === topicId); }
function setRoute(route) { document.querySelectorAll('.nav-item').forEach((item) => item.classList.toggle('active', item.dataset.route === route)); }
function subjectCard(subject) { return `<button class="subject-card" style="--card-color:${subject.color}" data-subject="${subject.id}"><span class="subject-count">${subject.topics.length} ${subject.topics.length === 1 ? 'тема' : 'темы'}</span><div class="subject-icon">${subject.icon}</div><h3>${esc(subject.title)}</h3><p>${esc(subject.description)}</p></button>`; }
function topicCard(subject, topic) { const done = state.progress[`${subject.id}/${topic.id}`]; return `<button class="topic-card" data-topic-subject="${subject.id}" data-topic="${topic.id}"><div><h3>${done ? '✓ ' : ''}${esc(topic.title)}</h3><div class="topic-meta">${esc(topic.difficulty)} · ${topic.minutes} мин</div></div><span class="topic-arrow">›</span></button>`; }

function renderHome() {
  setRoute('home');
  const firstSubject = subjectById('math'); const firstTopic = firstSubject?.topics[0];
  screen.innerHTML = `<section class="hero"><p class="eyebrow">Твоя учебная база</p><h1>Учись понятнее.<br><span style="color:#9a92ff">Шаг за шагом.</span></h1><p>Короткие объяснения, подробные решения и практика по предметам института — прямо внутри Telegram.</p></section><div class="search-box"><span>⌕</span><input id="searchInput" placeholder="Найти тему или предмет…" /></div><div class="section-row"><h2>Продолжить</h2><button class="link-button" data-topic-subject="${firstSubject?.id}" data-topic="${firstTopic?.id}">Открыть →</button></div><button class="continue-card" style="width:100%;text-align:left" data-topic-subject="${firstSubject?.id}" data-topic="${firstTopic?.id}"><span class="mini-icon">${firstSubject?.icon}</span><span style="flex:1"><h3>${firstTopic?.title}</h3><p>Высшая математика · ${state.progress[`${firstSubject?.id}/${firstTopic?.id}`] ? 'завершено' : 'начать изучение'}</p><span class="progress-bar"><span style="width:${state.progress[`${firstSubject?.id}/${firstTopic?.id}`] ? '100%' : '12%'}"></span></span></span><span class="topic-arrow">›</span></button><div class="section-row"><h2>Все предметы</h2><button class="link-button" data-route="subjects">Все →</button></div><div class="subject-grid">${state.subjects.map(subjectCard).join('')}</div>`;
  document.getElementById('searchInput').addEventListener('input', (event) => renderSearch(event.target.value));
}

function renderSearch(query) { const value = query.trim().toLowerCase(); if (!value) return renderHome(); const topics = state.subjects.flatMap((subject) => subject.topics.filter((topic) => `${subject.title} ${topic.title} ${topic.summary}`.toLowerCase().includes(value)).map((topic) => ({ subject, topic }))); setRoute('home'); screen.innerHTML = `<button class="back-button" data-route="home">← Назад</button><p class="eyebrow">Результаты поиска</p><h2>Нашли ${topics.length}</h2><div class="topic-list">${topics.length ? topics.map(({subject, topic}) => topicCard(subject, topic)).join('') : '<div class="empty"><span>⌕</span>Ничего не нашли. Попробуй другое слово.</div>'}</div>`; }
function renderSubjects() { setRoute('subjects'); screen.innerHTML = `<section class="hero"><p class="eyebrow">Библиотека знаний</p><h1>Предметы</h1><p>Выбирай направление и разбирай темы в своём темпе.</p></section><div class="subject-grid">${state.subjects.map(subjectCard).join('')}</div>`; }
function renderSubject(subjectId) { const subject = subjectById(subjectId); if (!subject) return renderSubjects(); setRoute('subjects'); screen.innerHTML = `<button class="back-button" data-route="subjects">← Все предметы</button><div class="topic-hero"><div class="subject-icon" style="color:${subject.color}">${subject.icon}</div><p class="eyebrow">${esc(subject.title)}</p><h1>Темы курса</h1><p>${esc(subject.description)}</p></div><div class="topic-list">${subject.topics.map((topic) => topicCard(subject, topic)).join('')}</div>`; }
function renderTopic(subjectId, topicId) { const subject = subjectById(subjectId); const topic = topicById(subjectId, topicId); if (!subject || !topic) return renderSubjects(); setRoute('subjects'); const saved = state.saved.includes(`${subjectId}/${topicId}`); screen.innerHTML = `<button class="back-button" data-subject="${subjectId}">← К списку тем</button><article><div class="topic-hero"><span class="badge">${esc(subject.title)} · ${esc(topic.difficulty)}</span><h1>${esc(topic.title)}</h1><p>${esc(topic.summary)}</p><button class="link-button" id="saveTopic">${saved ? '♥ Сохранено' : '♡ Сохранить тему'}</button></div><div class="objectives"><strong>После этой темы ты сможешь:</strong>${topic.objectives.map((item) => `<div class="objective">${esc(item)}</div>`).join('')}</div>${topic.sections.map((section) => `<section class="lesson-section"><h2>${esc(section.heading)}</h2><p>${esc(section.body)}</p><div class="formula">${esc(section.formula)}</div></section>`).join('')}<section class="example"><h3>Разберём пример</h3>${topic.example.steps.map((step, index) => `<div class="step"><span class="step-num">${index + 1}</span><span>${esc(step)}</span></div>`).join('')}<div class="answer">${esc(topic.example.answer)}</div></section><section class="quiz"><h3>Проверь себя</h3><p>${esc(topic.quiz.question)}</p><div id="quizOptions">${topic.quiz.options.map((option, index) => `<button class="quiz-option" data-answer="${index}">${esc(option)}</button>`).join('')}</div><p class="quiz-feedback" id="quizFeedback"></p></section><button class="primary-button" id="finishTopic">Отметить тему изученной</button></article>`; document.getElementById('saveTopic').addEventListener('click', () => { const key = `${subjectId}/${topicId}`; state.saved = state.saved.includes(key) ? state.saved.filter((item) => item !== key) : [...state.saved, key]; saveState(); renderTopic(subjectId, topicId); }); document.querySelectorAll('.quiz-option').forEach((button) => button.addEventListener('click', () => { const answer = Number(button.dataset.answer); document.querySelectorAll('.quiz-option').forEach((item) => item.disabled = true); button.classList.add(answer === topic.quiz.correct ? 'correct' : 'wrong'); if (answer !== topic.quiz.correct) document.querySelector(`[data-answer="${topic.quiz.correct}"]`).classList.add('correct'); document.getElementById('quizFeedback').textContent = `${answer === topic.quiz.correct ? 'Верно! ' : 'Почти. '}${topic.quiz.explanation}`; })); document.getElementById('finishTopic').addEventListener('click', () => { state.progress[`${subjectId}/${topicId}`] = true; saveState(); showToast('Тема отмечена как изученная'); renderTopic(subjectId, topicId); }); }
function renderSaved() { setRoute('saved'); const items = state.saved.map((key) => { const [subjectId, topicId] = key.split('/'); return { subject: subjectById(subjectId), topic: topicById(subjectId, topicId) }; }).filter((item) => item.subject && item.topic); screen.innerHTML = `<section class="hero"><p class="eyebrow">Твои закладки</p><h1>Сохранённое</h1><p>Темы, к которым удобно вернуться перед занятием или контрольной.</p></section>${items.length ? `<div class="topic-list">${items.map(({subject, topic}) => topicCard(subject, topic)).join('')}</div>` : '<div class="empty"><span>♡</span>Здесь пока пусто.<br>Сохрани тему, чтобы быстро найти её позже.</div>'}`; }
function renderProgress() { setRoute('progress'); const total = state.subjects.reduce((sum, subject) => sum + subject.topics.length, 0); const done = Object.values(state.progress).filter(Boolean).length; screen.innerHTML = `<section class="hero"><p class="eyebrow">Твой результат</p><h1>Прогресс</h1><p>Небольшие регулярные шаги дают большой результат.</p></section><div class="profile-head"><div class="big-avatar">${document.getElementById('profileAvatar').textContent}</div><div style="flex:1"><h2>Студент</h2><p>Уровень ${Math.max(1, Math.floor(done / 2) + 1)}</p><div class="progress-bar"><span style="width:${total ? Math.round(done / total * 100) : 0}%"></span></div></div></div><div class="stats-grid"><div class="stat"><strong>${done}</strong><span>тем изучено</span></div><div class="stat"><strong>${total - done}</strong><span>тем впереди</span></div><div class="stat"><strong>${state.saved.length}</strong><span>в закладках</span></div><div class="stat"><strong>${total ? Math.round(done / total * 100) : 0}%</strong><span>общий прогресс</span></div></div>`; }
function renderProfile() { screen.innerHTML = `<button class="back-button" data-route="home">← Назад</button><section class="profile-panel"><div class="profile-head"><div class="big-avatar">${document.getElementById('profileAvatar').textContent}</div><div><h2>Твой профиль</h2><p>Прогресс хранится на этом устройстве</p></div></div><div class="stats-grid"><div class="stat"><strong>${Object.values(state.progress).filter(Boolean).length}</strong><span>тем изучено</span></div><div class="stat"><strong>${state.saved.length}</strong><span>сохранено</span></div></div></section>`; }
function showToast(message) { const toast = document.getElementById('toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2300); }

document.addEventListener('click', (event) => { const routeButton = event.target.closest('[data-route]'); if (routeButton) { const route = routeButton.dataset.route; if (route === 'home') renderHome(); if (route === 'subjects') renderSubjects(); if (route === 'saved') renderSaved(); if (route === 'progress') renderProgress(); return; } const subjectButton = event.target.closest('[data-subject]'); if (subjectButton && !event.target.closest('[data-topic]')) { renderSubject(subjectButton.dataset.subject); return; } const topicButton = event.target.closest('[data-topic]'); if (topicButton) { renderTopic(topicButton.dataset.topicSubject, topicButton.dataset.topic); return; } });
document.getElementById('profileButton').addEventListener('click', renderProfile);

function init() { if (window.Telegram?.WebApp) { window.Telegram.WebApp.ready(); window.Telegram.WebApp.expand(); const user = window.Telegram.WebApp.initDataUnsafe?.user; if (user) { const initial = (user.first_name || 'У')[0].toUpperCase(); document.getElementById('profileAvatar').textContent = initial; } } if (!state.subjects.length) { screen.innerHTML = '<div class="empty">Не удалось загрузить учебную библиотеку.</div>'; return; } renderHome(); }
init();
