// Offline validation without a browser. Run: node checks/validate.cjs
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
let storage=new Map(),listeners={},writes=0;
const nodes=new Map();
function node(selector){if(!nodes.has(selector))nodes.set(selector,{value:'',dataset:{},style:{setProperty(){}},classList:{add(){},remove(){},toggle(){}},setAttribute(){},removeAttribute(){},focus(){},scrollIntoView(){},_html:'',set innerHTML(v){this._html=v;if(selector==='#screen')writes++;},get innerHTML(){return this._html;}});return nodes.get(selector);}
const context={window:{scrollTo(){},addEventListener(){}},document:{querySelector:node,querySelectorAll:()=>[],documentElement:node('html'),addEventListener:(k,f)=>listeners[k]=f,getElementById:id=>node('#'+id)},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)},location:{hash:''},setTimeout:()=>1,clearTimeout(){},console};
vm.createContext(context);for(const f of ['content.js','diagrams.js','app.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context,{filename:f});
const run=s=>vm.runInContext(s,context),data=context.window.STUDY_CONTENT,keys=new Set();let examples=0,practice=0,figures=0,sections=0;
for(const s of data.subjects)for(const t of s.topics){const key=s.id+'/'+t.id;assert(!keys.has(key),'Duplicate key: '+key);keys.add(key);assert(t.title&&t.summary&&t.objectives.length&&t.sections.length>=3,key+' incomplete');assert(t.examples.length&&t.practice.length,key+' missing exercises');assert(t.quiz.options.length>=3&&Number.isInteger(t.quiz.correct)&&t.quiz.correct>=0&&t.quiz.correct<t.quiz.options.length,key+' invalid quiz');examples+=t.examples.length;practice+=t.practice.length;sections+=t.sections.length;for(const sec of t.sections){assert(sec.body.length>30,key+' empty section');assert(!sec.body.includes('Схема:'),key+' unparsed figure');if(sec.diagram){assert(context.window.STUDY_DIAGRAMS.ids.includes(sec.diagram),key+' unknown figure');figures++;}}for(const ex of [...t.examples,...t.practice])assert(ex.title&&ex.answer&&ex.steps.length,key+' incomplete problem');const html=run(`lesson(${JSON.stringify(key)})`);assert(html.includes('id="quiz"')&&html.includes('id="practice"')&&html.includes('id="examples"'),key+' render failed');assert(!html.includes('undefined')&&!/\bNaN\b/.test(html),key+' invalid rendered text');}
for(const s of data.subjects)for(const t of s.topics)for(const k of t.links)assert(keys.has(k),'Broken lesson reference: '+k);
for(const s of data.subjects)assert(run(`course('${s.id}')`).includes(s.title));
// Multi-character search updates only the results container, preserving the search field.
context.location.hash='#courses';run('render()');const before=writes;node('#search').value='матриц';listeners.input({target:{id:'search',value:'матриц'}});assert.equal(writes,before);assert(node('#search-results').innerHTML.includes('Матрицы с нуля'));
listeners.input({target:{id:'search',value:'несуществующийтермин'}});assert(node('#search-results').innerHTML.includes('пока не нашлось'));
// Click handlers operate on the actual state and persistence code.
node('.lesson').dataset.key='math/matrices';const btn={dataset:{action:'save'},setAttribute(){}};listeners.click({target:{closest:()=>btn}});assert(JSON.parse(storage.get('study-pocket-saved')).includes('math/matrices'));
btn.dataset.action='complete';btn.classList={toggle(){}};btn.closest=()=>({querySelector:()=>node('completion-title')});listeners.click({target:{closest:()=>btn}});assert.equal(JSON.parse(storage.get('study-pocket-progress'))['math/matrices'],true);listeners.click({target:{closest:()=>btn}});assert.equal(JSON.parse(storage.get('study-pocket-progress'))['math/matrices'],false);
const quiz=data.subjects[0].topics.find(t=>t.id==='matrices').quiz;btn.dataset={option:String(quiz.correct)};listeners.click({target:{closest:()=>btn}});assert(node('#quiz-feedback').innerHTML.includes('Верно.'));btn.dataset={option:String((quiz.correct+1)%3)};listeners.click({target:{closest:()=>btn}});assert(node('#quiz-feedback').innerHTML.includes('Пока не совсем.'));
// Startup survives malformed or unavailable local storage.
for(const mode of ['malformed','unavailable']){const c={...context,window:{scrollTo(){},addEventListener(){}},localStorage:{getItem(){if(mode==='unavailable')throw Error('disabled');return '{broken';},setItem(){if(mode==='unavailable')throw Error('disabled');}}};vm.createContext(c);for(const f of ['content.js','diagrams.js','app.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),c);}
assert.equal(keys.size,71);
console.log(JSON.stringify({status:'passed',topics:keys.size,sections,workedExamples:examples,practiceProblems:practice,quizzes:keys.size,figurePlacements:figures,svgDefinitions:context.window.STUDY_DIAGRAMS.ids.length,checks:['all lesson renderers','content integrity','cross-topic references','search without full-page replacement','bookmarks','completion and undo','quiz feedback','malformed and unavailable storage'],limits:'DOM mocked; no browser layout or Telegram device testing'},null,2));
